### ISSUE TITLE
Comments are unreadable when selected in Code Review

### ISSUE THREAD

**Issue by SageChaozu** [dracula/visual-studio#21]
In Visual Studio, you have the ability to request reviews and place comments on the reviews. If you decide to select a comment in the code review, the text and background are the same value making it unreadable.

In the screen shot, you will see the red rectangle where the comment should display. At first you would think its a blank space, but you will see the check box to the right that allows you to mark the item as done. 

![image](https://user-images.githubusercontent.com/14968502/170632814-53cb5a2c-74d8-40d8-8e26-d7e44a95f209.png)

**Comment by luxonauta** [comment]
We've pushed some fixes since the opening of this Issue. 🦇 Is it possible for you to check if the same thing happens in the latest versions? 🤔

**Comment by SageChaozu** [comment]
I just downloaded the latest version put on the Microsoft marketplace (https://marketplace.visualstudio.com/items?itemName=dracula-theme.dracula)  and I still see the same issue. 

I forgot to add some additional information about the issue when I put the item in. When you see the comments initially in the review you will notice they are visible and I assume this is the "unselected" state. As soon as I click on the comment it makes the text unviewable and I think that maybe the "selected" state for that control. I'm not sure how it looks in the Theme file but I suspect it has something to do with selected or has focus. 

Screenshot:
![InvisibleCommentIssue](https://user-images.githubusercontent.com/14968502/191400951-651a6df1-4d81-41ba-bd4e-92fdde12a752.png)

**Comment by TheXenocide** [comment]
I am also experiencing this issue and I believe @SageChaozu is correct about the selected/highlighted state of the comment. In order to read a comment once it has been selected I have to select a different comment (or add one there are no other comments) in order for the text to become visible again. This is particularly inconvenient in the sense that you click on a comment in order to view the lines of code that it pertains to, so in order to read the code you have to not be able to read the comment and when you click on a different comment so you can read this one it jumps to a different place in code.
